### ISSUE TITLE
Cannot install libudev-devel on centos:latest

### ISSUE THREAD

**Issue by wkatsak** [CentOS/sig-cloud-instance-images#26] opened 2015-07-16 01:26 UTC
Hello,

I am having an issue installing libudev-devel on the centos:centos7 Docker.

My output looks like this:

```
[root@704151a1f239 /]# yum install libudev-devel

...

Dependencies Resolved

====================================================================================================================
 Package                         Arch                Version                             Repository            Size
====================================================================================================================
Installing:
 systemd-devel                   x86_64              208-20.el7_1.5                      updates              153 k
Installing for dependencies:
 acl                             x86_64              2.2.51-12.el7                       base                  81 k
 cryptsetup-libs                 x86_64              1.6.6-3.el7                         base                 179 k
 dbus                            x86_64              1:1.6.12-11.el7                     base                 306 k
 device-mapper                   x86_64              7:1.02.93-3.el7_1.1                 updates              209 k
 device-mapper-libs              x86_64              7:1.02.93-3.el7_1.1                 updates              259 k
 fipscheck                       x86_64              1.4.1-5.el7                         base                  21 k
 fipscheck-lib                   x86_64              1.4.1-5.el7                         base                  11 k
 kmod                            x86_64              14-10.el7                           base                  78 k
 kmod-libs                       x86_64              14-10.el7                           base                  46 k
 qrencode-libs                   x86_64              3.4.1-3.el7                         base                  50 k
 systemd                         x86_64              208-20.el7_1.5                      updates              2.6 M
 systemd-libs                    x86_64              208-20.el7_1.5                      updates              161 k
 tcp_wrappers-libs               x86_64              7.6-77.el7                          base                  66 k

Transaction Summary
====================================================================================================================
Install  1 Package (+13 Dependent packages)

Total download size: 4.2 M
Installed size: 15 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/base/packages/cryptsetup-libs-1.6.6-3.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for cryptsetup-libs-1.6.6-3.el7.x86_64.rpm is not installed
(1/14): cryptsetup-libs-1.6.6-3.el7.x86_64.rpm                                               | 179 kB  00:00:01     
(2/14): fipscheck-1.4.1-5.el7.x86_64.rpm                                                     |  21 kB  00:00:00     
Public key for device-mapper-libs-1.02.93-3.el7_1.1.x86_64.rpm is not installed
(3/14): device-mapper-libs-1.02.93-3.el7_1.1.x86_64.rpm                                      | 259 kB  00:00:02     
(4/14): acl-2.2.51-12.el7.x86_64.rpm                                                         |  81 kB  00:00:02     
(5/14): fipscheck-lib-1.4.1-5.el7.x86_64.rpm                                                 |  11 kB  00:00:00     
(6/14): kmod-libs-14-10.el7.x86_64.rpm                                                       |  46 kB  00:00:00     
(7/14): device-mapper-1.02.93-3.el7_1.1.x86_64.rpm                                           | 209 kB  00:00:02     
(8/14): qrencode-libs-3.4.1-3.el7.x86_64.rpm                                                 |  50 kB  00:00:00     
(9/14): systemd-devel-208-20.el7_1.5.x86_64.rpm                                              | 153 kB  00:00:00     
(10/14): kmod-14-10.el7.x86_64.rpm                                                           |  78 kB  00:00:01     
(11/14): tcp_wrappers-libs-7.6-77.el7.x86_64.rpm                                             |  66 kB  00:00:00     
(12/14): dbus-1.6.12-11.el7.x86_64.rpm                                                       | 306 kB  00:00:03     
(13/14): systemd-libs-208-20.el7_1.5.x86_64.rpm                                              | 161 kB  00:00:01     
(14/14): systemd-208-20.el7_1.5.x86_64.rpm                                                   | 2.6 MB  00:00:05     
--------------------------------------------------------------------------------------------------------------------
Total                                                                               558 kB/s | 4.2 MB  00:00:07     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-1.1503.el7.centos.2.8.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Is this ok [y/N]: y
Running transaction check
Running transaction test


Transaction check error:
  file /usr/lib64/libsystemd-daemon.so.0.0.10 from install of systemd-libs-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-id128.so.0.0.26 from install of systemd-libs-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-journal.so.0.11.3 from install of systemd-libs-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-login.so.0.9.1 from install of systemd-libs-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libudev.so.1.4.0 from install of systemd-libs-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/security/pam_systemd.so from install of systemd-libs-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /etc/rc.d/rc.local from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/journalctl from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/localectl from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/loginctl from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemctl from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-ask-password from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-cat from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-coredumpctl from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-detect-virt from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-inhibit from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-machine-id-setup from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-notify from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-run from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-tmpfiles from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/systemd-tty-ask-password-agent from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/bin/udevadm from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/system-generators/systemd-rc-local-generator from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/system/console-getty.service from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-ac-power from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-activate from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-binfmt from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-cgroups-agent from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-coredump from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-fsck from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-initctl from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-journald from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-localed from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-logind from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-multi-seat-x from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-random-seed from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-remount-fs from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-reply-password from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-shutdown from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-shutdownd from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-sleep from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-sysctl from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-udevd from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-update-utmp from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-user-sessions from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/systemd/systemd-vconsole-setup from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/accelerometer from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/ata_id from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/cdrom_id from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/collect from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/mtd_probe from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/rules.d/40-redhat.rules from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/scsi_id from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/lib/udev/v4l_id from install of systemd-208-20.el7_1.5.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64

Error Summary
-------------
```

It seems the issue is with libudev-devel trying to install regular systemd instead of container systemd. The weird thing is that I was able to install this no problem about a month ago, using the same docker configuration.

Any ideas?

Thanks,
Bill Katsak

**Comment by jperrin** [comment] 2015-07-16 01:42
There's been an update to systemd in the last month. It may be that we need to rebuild systemd-container to reflect the new version number. If you're able run without dealing with systemd, or you can deal with the restrictions that come with it, you can work around this with the following

```
RUN yum -y swap -- remove systemd-container systemd-container-libs -- install systemd systemd-libs
```

**Comment by wkatsak** [comment] 2015-07-16 01:52
Thanks, I'll try this. Further investigation shows that the centos7 docker is missing systemd-container-devel in general (it doesn't show in the repo, even though it should be in extras). Is there any intentional reason for this?

**Comment by wkatsak** [comment] 2015-07-16 01:58
Ok, I figured something out. Forgive me, I don't quite fully understand how this build ecosystem works yet.

I found this file on sig-cloud-instance-build:
    https://github.com/CentOS/sig-cloud-instance-build/blob/master/docker/centos-7.ks

This seems to be setting up a systemd repo in this bit:

```
# Create repo for systemd-container
cat >/etc/yum.repos.d/systemd.repo <<EOF
[systemdcontainer]
name=CentOS-\$releasever - systemd-container
baseurl=http://dev.centos.org/centos/7/systemd-container/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

EOF
```

Is this file used to build the centos docker? In any event, added this to my dockerfile:

```
RUN bash -c 'echo [systemdcontainer] >> /etc/yum.repos.d/systemd.repo'
RUN bash -c 'echo name=CentOS-\$releasever - systemd-container >> /etc/yum.repos.d/systemd.repo'
RUN bash -c 'echo baseurl=http://dev.centos.org/centos/7/systemd-container >> /etc/yum.repos.d/systemd.repo'
RUN bash -c 'echo gpgcheck=1 >> /etc/yum.repos.d/systemd.repo'
RUN bash -c 'echo enabled=1 >> /etc/yum.repos.d/systemd.repo'
RUN bash -c 'echo gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 >> /etc/yum.repos.d/systemd.repo'
RUN bash -c 'yum clean all'
RUN bash -c 'yum -y install systemd-container-devel'
```

and it now seems to work fine.

Thoughts? Am I completely off base here?

**Comment by wkatsak** [comment] 2015-07-16 17:57
This seems weird to me, I built the docker from centos-7-20150616_1752-docker.tar.xz and this /etc/yum.repos.d/systemd.repo isn't there. Is this intended behavior? Am I missing something about how this build works?

**Comment by jperrin** [comment] 2015-07-16 19:11
hmm. Indeed it's not in the generated image properly. I'll investigate and push an update.

**Comment by mboes** [comment] 2015-11-23 19:15
I'm getting hit by this issue as well still, using `centos:7` as the base image. To reproduce:

```
FROM centos:centos7

RUN yum -y install systemd-devel
```

**Comment by jperrin** [comment] 2015-11-23 19:19
This is not proper for the current container build, but should be once the next version of 7 is available as a container. 

For now you would need to follow the advice given earlier in this issue.

**Comment by mboes** [comment] 2015-11-23 19:19
Actually `/etc/yum.repos.d/systemd.repo` _is_ there now, but in a Docker container I should `yum install  systemd-container-devel` instead. Is there a way to consider `systemd-devel` a virtual resource that can be provided by either `systemd-devel` or `systemd-container-devel`, so that I don't need to change my provisioning scripts depending on whether I'm in a docker container or in a VM?

**Comment by jperrin** [comment] 2015-11-23 19:21
Not yet. the next iteration of the container will be based on the code for 7.2, and will just have systemd. no more systemd-container or fakesystem mess to clean up.

**Comment by mboes** [comment] 2015-11-23 19:21
Awesome, thanks.

**Comment by yajo** [comment] 2015-12-15 10:02
Just want to let you know that installing `openldap-devel` fails the same way. What's exactly the workaround now? I see many ideas and I don't know which one is the good one.

**Comment by jfarrell** [comment] 2015-12-15 13:57
An package update must have just gone out recently as I hit this with several packages yesterday that where previously not experiencing this problem, all relating to systemd-container and systemd-container-libs conflicts, broken packages including packages like `httpd`, `java-1.7.0-openjdk`. Installing systemd-container-devel solved the problem as a workaround, but that does not feel like a long term solution.  @jperrin any ideas as to when 7.2 centos container will be available?

**Comment by mboes** [comment] 2015-12-15 14:03
@jfarrell you're right. In my experience `initscripts` gained a new dependency on systemd, and that's what's causing all these new conflicts. It all started this weekend, maybe a bit earlier.

**Comment by jperrin** [comment] 2015-12-15 14:19
7.2 was released GA yesterday, and I'm building the new container now. HOWEVER, there's a systemd-container-EOL package in the systemd-container repository that should obsolete all the packages and pull in the new systemd packages.

in 7.2, the container will simply use the base systemd package, so we won't have to do any package swaps or changes as noted above.

**Comment by jperrin** [comment] 2015-12-15 21:38
The updated (7.2.1511) container is now available in the docker registry. a `docker pull centos` will solve all of this. Closing the bug since this is fixed in the current release.

**Closed as completed by jperrin** 2015-12-15 21:38 UTC
