### ISSUE TITLE
The centos:centos7 image doesn't have "service" command

### ISSUE THREAD

**Issue by jamshid** [CentOS/sig-cloud-instance-images#28] opened 2015-08-27 18:19 UTC
I know centos7 switched to systemd but I thought "service MYSERVICE start" is still supported for backwards compatibility. That's mentioned in below blog and I see /sbin/service in an official CentOS-7-x86_64-Minimal-1503-01.iso vm.

How do I add the "service" command to a centos7 container?

```
$ docker run -ti centos:centos6 service
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
$ docker run -ti centos:centos7 service
exec: "service": executable file not found in $PATH
Error response from daemon: Cannot start container ...
$ docker run -ti centos:centos7 which service
which: no service in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

http://www.knowledgepia.com/en/k-blog/linux-server/linux-systemd-on-rhel-centos7

> To view, start, stop, restart, enable, or disable system services you will use the systemctl instead of the old service command.
> Note: for backwards compatibility the old service command is still available in CentOS 7 and it will redirect any command to the new systemctl utility.

**Comment by jperrin** [comment] 2015-08-27 18:24
You would need to install the 'initscripts' package as part of your Dockerfile.. Additionally you would need to enable systemd in the Dockerfile. An example is listed in the base container Dockerfile at https://github.com/CentOS/sig-cloud-instance-images/blob/CentOS-7/docker/Dockerfile#L10

**Comment by jamshid** [comment] 2015-08-28 01:48
Thanks, in hindsight I guess I could have run `yum whatprovides service`. In my case I don't need full systemd, my container just has some existing scripts using "service".

Since /sbin/service appears to be pre-installed on standard(?) CentOS7 it seems best if the docker image preinstalls it, but maybe there's a reason for the difference. Feel free to close this.

**Comment by shadowbq** [comment] 2015-11-09 21:10
+1 why no initscripts?

**Comment by jperrin** [comment] 2015-11-09 21:23
Because they're not the default init system in el7, and most users aren't using systemd in the container to start services.

**Comment by jperrin** [comment] 2015-12-15 21:36
forgot to close this one. marking closed.

**Closed as completed by jperrin** 2015-12-15 21:36 UTC

**Comment by eduardocerqueira** [comment] 2016-10-23 15:43
I see this issue is already closed, just would like to share a little bit more detail how to fix it based on recommendation to install initscripts on centOS base image, I guess it can be helpful for people still beginners with docker and gets this page.

in your DockerFile just add the line:

`RUN yum -y install initscripts && yum clean all`

that is it!

**Comment by samratBasra** [comment] 2016-12-02 04:12
yum install initscripts

**Comment by hapylestat** [comment] 2017-01-12 07:17
@eduardocerqueira i agree that initscripts package will save many lives, but ppl need to consider stop using obsolete commands, which solves problem too :)

**Comment by geerlingguy** [comment] 2017-06-07 13:53
Just noticed that initscripts _used_ to be included in the base CentOS 6 image, but is no longer (sometime in the past week or two it seems it's been removed). Therefore for those unfortunate souls still using CentOS 6 and requiring `init`, make sure you `yum -y install initscripts` as part of your Dockerfile!

**Comment by ghost** [comment] 2017-07-22 14:40
Is there any workaround to do this: first need to run a container with /sbin/init so PID 1 is 'init', then another entrypoint script like 'setup_and_startup_chef12.sh' triggers during the container startup?

**Comment by jperrin** [comment] 2017-07-22 17:16
@honglzh, you just need to install the initscripts package as part of your container build. If you scroll up further in this bug you'll see the command structure to do this.

**Comment by FatihaBiga** [comment] 2018-09-07 09:51
in my case,i want it to start firewall service
but both this commands give the same results
#service firewalld start
#systemctl start firewalld.services
they both show this output:Failed to get D-Bus connection: Operation not permitted
even that i have the dbus installed and also the systemctl 
i did yum -y install initscripts  by the way but still have the same problem
anything to help ??

**Comment by jperrin** [comment] 2018-09-07 20:35
@FatihaBiga dbus isn't able to properly run inside a container without a bit of magic, mounting it back into the host OS. This means you also need dbus running for the host. 

Are you looking to have firewalld in a container modifying the host's networking?

**Comment by FatihaBiga** [comment] 2018-09-10 09:21
@jperrin  yes i want to install firewall and other services inside the container.
instead of mounting a volume,can't i just copying it inside the container from the host?? and how to do it
cause i'm trying to build containers as a service for my team.
they only have to pull the images and do a simple run and have the envirenemnet set and ready to be used

**Comment by jperrin** [comment] 2018-09-10 17:48
No, you cannot copy the dbus pieces into the container, nor can you modify firewall rules from entirely inside the container. Network traffic (and the rules) are handled by the kernel. Firewalld and iptables are just the userspace tools for interacting with them. 

In short, you're going to need to take a hard look at how you're doing this and why. You can't simply rub some containers on your deploys.

**Comment by datdinhquoc** [comment] 2020-05-31 07:41
> yum install initscripts

The problem is on my CentOS, after installing `initscripts`, the binary 'service' redirects to 'systemctl' which relies on systemd.

How to solve this problem?
